const CART_TYPES = {
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  EDIT_CART: 'EDIT_CART',
  GET_CART_ITEMS: 'GET_CART_ITEMS',
  GET_ACTIVE_CART_ITEMS: 'GET_ACTIVE_CART_ITEMS',
  CLEAR_STORE_CART: 'CLEAR_STORE_CART',
  EDIT_CART_QUANTITY: 'EDIT_CART_QUANTITY',
  CHECKOUT_CART: 'CHECKOUT_CART',
  ADMIN_PREV_ORDERS: 'ADMIN_PREV_ORDERS',
};

export default CART_TYPES;
